### ISSUE TITLE
What is this? :D

### ISSUE THREAD

**Issue by shivabhusal** [bipashant/Hungarian-Algorithm---Ruby#1]

**Comment by bipashant** [comment]
The Hungarian method is a [combinatorial optimization](https://en.wikipedia.org/wiki/Combinatorial_optimization) [algorithm](https://en.wikipedia.org/wiki/Algorithm) that solves the [assignment problem](https://en.wikipedia.org/wiki/Assignment_problem) in [polynomial time](https://en.wikipedia.org/wiki/Polynomial_time) and which anticipated later [primal–dual methods](https://en.wikipedia.org/wiki/Duality_(optimization)). It was developed and published in 1955 by [Harold Kuhn](https://en.wikipedia.org/wiki/Harold_Kuhn), who gave the name "Hungarian method" because the algorithm was largely based on the earlier works of two [Hungarian](https://en.wikipedia.org/wiki/Hungary) mathematicians: [Dénes Kőnig](https://en.wikipedia.org/wiki/D%C3%A9nes_K%C5%91nig) and [Jenő Egerváry](https://en.wikipedia.org/wiki/Jen%C5%91_Egerv%C3%A1ry) 😛
